language: node_js

node_js: stable  # 要安装的node版本为当前的稳定版

cache:
  directories:
    - node_modules # 要缓存的文件夹

before_install:
  - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:   # 最后执行的命令
  - cd ./public
  - git init
  - git config user.name "MarchNineteen"
  - git config user.email "1501987783@qq.com"
  - git add .
  - git commit -m "sfdsfd"
  - git push --force --quiet "https://${new}@${GH_REF}" master:gh-pages



branches:
  only:
    - master # 触发持续集成的分支

env:
  global:
    - GH_REF: github.com/MarchNineteen/blog.git
